address_descriptors = false
custom_script = ""
google_tag_manager = ""
author = "Courtoise Resourcerie, Luc Van De Velde"
copyright = "Copyright © 2024 lacourtoiseressourcerie.com - La Courtoise Ressourcerie"
description = "Le réemploi, plus écolo que le recyclage"
keywords = "courtoise, ressourcerie, reemploi, ecolo, recyclage, sived, insertion, collecte, saint-maximin-la-sainte-baume, brignoles"
email = "secretariat@courtoiseressourcerie.com"
phone = "04 94 72 01 50"
location = """
90 Chemin de Bonneval - Quartier La Courtoise 83470 Saint-Maximin-la-Sainte-Beaume
"""
favicon = "/images/favicon.png"
image = "/images/logo.png"
logo = "/images/logo.png"
logoDefaultHeight = "50px"
logoNav = "/images/logonav.png"
logo_text = "La Courtoise Ressourcerie"
logo_width = "150px"
navbar_fixed = false

[baidu]
analytics_id = ""
enable = false

[contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false

[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2

[counter]
enable = false
username = "lvandevelde"

[mailchimp]
enable = true

[navigation_button]
enable = true
label = "get a quote"
link = "contact"

[plausible]
domain = ""
enable = false

[preloader]
enable = false
preloader = ""

[site_verification]
baidu = ""
bing = ""
google = ""

[widgets]
sidebar = [ "recent_posts", "taxonomy_category", "taxonomy_tags" ]

[gmap]
enable = false
gmap_api = "AIzaSyCUyldSJJJbPecWby4i5HLODlZYPwp7ZkA"
map_latitude = "43.44988099320413"
map_longitude = "5.887806938320934"
map_marker = "/imagesimages/marker.png"

[osm]
enable = true
map = "//umap.openstreetmap.fr/fr/map/carte-sans-nom_706905"

[matomo]
enable = true
id = "1"
url = "https://yunohost.courtoiseressourcerie.com/matomo/"

[[footerlogo]]
icon = "/images/footer/Republique.png"
title = "République Française"

[[footerlogo]]
icon = "/images/image001.jpg"
title = "Ma Region Sud"

[[footerlogo]]
icon = "/images/footer/Var.png"
title = "Var"

[[footerlogo]]
icon = "/images/logo-ademe-2020-898x1024.jpg"
title = "logo ADEME"

[[footerlogo]]
icon = "/images/footer/SIVED-CAPV.png"
title = "Sived83"

[[footerlogo]]
icon = "/images/footer/logo-4R-reseau-ressourceries-recycleries-paca.png"
title = "Ressourcerie"

[[footerlogo]]
icon = "/images/r2.png"
title = "Chantier école"

[[footerlogo]]
icon = "/images/oip-photoroom1.png"
title = "Ecologic"

[[footerlogo]]
icon = "/images/footer/Logo_Ecomaison.png"
title = "Ecomaison"

[[footerlogo]]
icon = "/images/footer/logo_Valdelia_avec_baseline.png"
title = "Valdelia"

[[social]]
icon = "fab fa sived83"
title = "sived"
link = "https://sived83.com/le-service/ressourcerie-la-courtoise/"

[[social]]
icon = "fab fa-facebook"
title = "facebook"
link = "https://www.facebook.com/courtoiseressourcerie/"

[[social]]
icon = "fab fa-instagram"
title = "instagram"
link = "https://www.instagram.com/la_courtoise_ressourcerie/"

[[social]]
icon = "fab fa labelemmaüs"
title = "labelemmaüs"
link = "https://www.label-emmaus.co/fr/nos-boutiques/la-courtoise-ressourcerie/"

[[social]]
icon = "fab fa-github"
title = "github"
link = "https://gitlab.com/courtoise"
